<?php

declare(strict_types=1);

namespace Nola\Deploy\Util;

class MaintenancePageHandler
{
    private string $errorsDir;
    private string $skinDir;
    private string $designXml;
    private string $designXmlBackup;

    public function __construct(
        private ConfigLoader $config,
        private Logger $logger,
    ) {
        $root = $config->getMagentoRoot();
        $this->errorsDir = $root . '/pub/errors';
        $this->skinDir = $this->errorsDir . '/nola-deploy';
        $this->designXml = $this->errorsDir . '/design.xml';
        $this->designXmlBackup = $this->errorsDir . '/design.xml.nola-backup';
    }

    /**
     * Install custom maintenance page before enabling maintenance mode.
     * Creates nola-deploy error skin and switches design.xml to use it.
     */
    public function install(): void
    {
        $this->logger->info('Installing custom maintenance page');

        // Create skin directory
        if (!is_dir($this->skinDir)) {
            mkdir($this->skinDir, 0755, true);
        }

        // Write page.phtml — passthrough that renders full HTML from 503.phtml
        $pagePhtml = $this->skinDir . '/page.phtml';
        file_put_contents($pagePhtml, "<?php require \$contentTemplate; ?>\n");

        // Resolve maintenance HTML content
        $html = $this->resolveMaintenanceHtml();

        // Write 503.phtml — contains the full HTML page
        $content503 = "<?php\n// Generated by nola-deploy — do not edit\n?>\n" . $html;
        file_put_contents($this->skinDir . '/503.phtml', $content503);

        // Backup original design.xml and switch to nola-deploy skin
        if (file_exists($this->designXml) && !file_exists($this->designXmlBackup)) {
            copy($this->designXml, $this->designXmlBackup);
        }

        $skinXml = "<?xml version=\"1.0\"?>\n<config>\n    <skin>nola-deploy</skin>\n</config>\n";
        file_put_contents($this->designXml, $skinXml);

        $this->logger->info('Maintenance skin installed at pub/errors/nola-deploy/');
    }

    /**
     * Restore original design.xml after maintenance mode is disabled.
     */
    public function restore(): void
    {
        if (file_exists($this->designXmlBackup)) {
            copy($this->designXmlBackup, $this->designXml);
            unlink($this->designXmlBackup);
            $this->logger->info('Restored original maintenance page skin');
        }
    }

    /**
     * Read user's HTML file first, fall back to bundled template.
     */
    private function resolveMaintenanceHtml(): string
    {
        $root = $this->config->getMagentoRoot();
        $userPage = $this->config->getMaintenancePage();

        // Resolve user page path (relative to Magento root or absolute)
        $userPath = str_starts_with($userPage, '/') ? $userPage : $root . '/' . $userPage;

        if (file_exists($userPath)) {
            $this->logger->info("Using custom maintenance page: {$userPage}");
            return file_get_contents($userPath);
        }

        // Fallback to bundled template
        $bundled = dirname(__DIR__, 2) . '/templates/maintenance.html';
        if (file_exists($bundled)) {
            $this->logger->info('Using default nola-deploy maintenance page');
            return file_get_contents($bundled);
        }

        // Absolute fallback
        return '<html><body><h1>Maintenance in progress</h1></body></html>';
    }
}
